# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peasantlegaldb', '0003_auto_20180714_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('archives', models.ManyToManyField(to='peasantlegaldb.Archive')),
                ('cases', models.ManyToManyField(to='peasantlegaldb.Case')),
                ('people', models.ManyToManyField(to='peasantlegaldb.Person')),
                ('records', models.ManyToManyField(to='peasantlegaldb.Record')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('villages', models.ManyToManyField(to='peasantlegaldb.Village')),
            ],
        ),
    ]
