# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('court_type', models.IntegerField(choices=[(2, 'Tourn'), (1, 'Hallmoot'), (5, 'Unknown'), (6, 'Account Roll'), (3, 'Impercamentum'), (4, 'Chevage')])),
                ('of_interest', models.BooleanField(default=False)),
                ('ad_legem', models.BooleanField(default=False)),
                ('villeinage_mention', models.BooleanField(default=False)),
                ('active_sale', models.BooleanField(default=False)),
                ('incidental_land', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CasePeopleLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villeinage', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_land', to='peasantlegaldb.Case')),
            ],
            options={
                'verbose_name_plural': 'Cases to People to Land',
                'verbose_name': 'Case to Person to Land',
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Case Types',
                'verbose_name': 'Case Type',
            },
        ),
        migrations.CreateModel(
            name='Chattel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Chevage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross', models.BooleanField(default=False)),
                ('recessit', models.BooleanField(default=False)),
                ('habet_terram', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cornbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Case')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Chattel')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Extrahura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Chattel')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Heriot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=25)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Chattel')),
            ],
        ),
        migrations.CreateModel(
            name='Hundred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.County')),
            ],
        ),
        migrations.CreateModel(
            name='Impercamentum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Impercamenta',
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('owner_chain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('land', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Land')),
            ],
            options={
                'verbose_name_plural': 'Land Parcels',
                'verbose_name': 'Land Parcel',
            },
        ),
        migrations.CreateModel(
            name='LandSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_land_parcel', to='peasantlegaldb.Land')),
                ('old_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_land_parcel', to='peasantlegaldb.Land')),
            ],
            options={
                'verbose_name_plural': 'Land Splits',
                'verbose_name': 'Land Split',
            },
        ),
        migrations.CreateModel(
            name='Litigant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_notes', models.TextField()),
                ('ad_proximum', models.BooleanField(default=False)),
                ('distrained', models.BooleanField(default=False)),
                ('attached', models.BooleanField(default=False)),
                ('bail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=150)),
                ('in_denarius', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Murrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('notes', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Chattel')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Case')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelTenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Parcel Tenures',
                'verbose_name': 'Parcel Tenure',
            },
        ),
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Parcel Types',
                'verbose_name': 'Parcel Type',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('relation_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[('V', 'Villein'), ('I', 'Institution'), ('U', 'Unknown'), ('F', 'Free')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('U', 'Unknown'), ('I', 'Institution'), ('F', 'Female')], max_length=1)),
                ('tax_1332', models.FloatField()),
                ('tax_1379', models.FloatField()),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PlaceMentioned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Case')),
            ],
            options={
                'verbose_name_plural': 'Places Mentioned',
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_pledge', to='peasantlegaldb.Case')),
                ('pledge_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_giver', to='peasantlegaldb.Person')),
                ('pledge_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_receiver', to='peasantlegaldb.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definitive', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Position Names',
                'verbose_name': 'Position Name',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('record_type', models.IntegerField(choices=[(4, 'Custumal'), (2, 'Extant'), (6, 'Account Roll'), (5, 'Patent Roll'), (1, 'Court Roll'), (3, 'Survey')])),
                ('reel', models.IntegerField()),
                ('notes', models.TextField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Archive')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Relation Types',
                'verbose_name': 'Relation Type',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definitive', models.BooleanField(default=False)),
                ('person_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_one', to='peasantlegaldb.Person')),
                ('person_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_two', to='peasantlegaldb.Person')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Relation')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('law_term', models.IntegerField(choices=[(2, 'Easter'), (1, 'Hilary'), (4, 'Michaelmas'), (3, 'Trinity')])),
                ('folio', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Record')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ancient_demesne', models.BooleanField(default=False)),
                ('great_rumor', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.County')),
                ('hundred', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Hundred')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Village'),
        ),
        migrations.AddField(
            model_name='position',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Session'),
        ),
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.PositionType'),
        ),
        migrations.AddField(
            model_name='placementioned',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Village'),
        ),
        migrations.AddField(
            model_name='person',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Village'),
        ),
        migrations.AddField(
            model_name='litigant',
            name='amercement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigant_amercement', to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='litigant',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_person', to='peasantlegaldb.Case'),
        ),
        migrations.AddField(
            model_name='litigant',
            name='damage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigant_damages', to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='litigant',
            name='fine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigant_fine', to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='litigant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_to_case', to='peasantlegaldb.Person'),
        ),
        migrations.AddField(
            model_name='litigant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litigant_role', to='peasantlegaldb.Role'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='parcel_tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.ParcelTenure'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='parcel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.ParcelType'),
        ),
        migrations.AddField(
            model_name='impercamentum',
            name='amercement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='impercamentum',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Chattel'),
        ),
        migrations.AddField(
            model_name='impercamentum',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_impercamentum', to='peasantlegaldb.Case'),
        ),
        migrations.AddField(
            model_name='impercamentum',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Person'),
        ),
        migrations.AddField(
            model_name='heriot',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='heriot',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_heriot', to='peasantlegaldb.Case'),
        ),
        migrations.AddField(
            model_name='heriot',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Person'),
        ),
        migrations.AddField(
            model_name='extrahura',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='cornbot',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='chevage',
            name='amercement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Money'),
        ),
        migrations.AddField(
            model_name='chevage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_chevage', to='peasantlegaldb.Case'),
        ),
        migrations.AddField(
            model_name='chevage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Person'),
        ),
        migrations.AddField(
            model_name='casepeopleland',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Land'),
        ),
        migrations.AddField(
            model_name='casepeopleland',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Person'),
        ),
        migrations.AddField(
            model_name='casepeopleland',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Role'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.CaseType'),
        ),
        migrations.AddField(
            model_name='case',
            name='litigants',
            field=models.ManyToManyField(through='peasantlegaldb.Litigant', to='peasantlegaldb.Person'),
        ),
        migrations.AddField(
            model_name='case',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Session'),
        ),
        migrations.AddField(
            model_name='case',
            name='verdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.Verdict'),
        ),
    ]
