# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(1, 'Hallmoot'), (4, 'Chevage'), (3, 'Impercamentum'), (5, 'Unknown'), (2, 'Tourn'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('U', 'Unknown'), ('M', 'Male'), ('I', 'Institution')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[('F', 'Free'), ('U', 'Unknown'), ('V', 'Villein'), ('I', 'Institution')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(1, 'Court Roll'), (3, 'Survey'), (4, 'Custumal'), (6, 'Account Roll'), (5, 'Patent Roll'), (2, 'Extant')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(1, 'Hilary'), (4, 'Michaelmas'), (2, 'Easter'), (3, 'Trinity')]),
        ),
    ]
