# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='owner_chain',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(4, 'Chevage'), (5, 'Unknown'), (1, 'Hallmoot'), (3, 'Impercamentum'), (2, 'Tourn'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[('M', 'Male'), ('I', 'Institution'), ('F', 'Female'), ('U', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[('I', 'Institution'), ('V', 'Villein'), ('U', 'Unknown'), ('F', 'Free')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(3, 'Survey'), (1, 'Court Roll'), (2, 'Extant'), (4, 'Custumal'), (5, 'Patent Roll'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(1, 'Hilary'), (4, 'Michaelmas'), (2, 'Easter'), (3, 'Trinity')]),
        ),
    ]
