# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0002_auto_20170830_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationshipType',
            new_name='Relation',
        ),
        migrations.RenameModel(
            old_name='PeopleRelationship',
            new_name='Relationship',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='relation_type',
            new_name='relation',
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(5, 'Unknown'), (1, 'Hallmoot'), (3, 'Impercamentum'), (2, 'Tourn'), (6, 'Account Roll'), (4, 'Chevage')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[('I', 'Institution'), ('U', 'Unknown'), ('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(5, 'Patent Roll'), (2, 'Extant'), (1, 'Court Roll'), (4, 'Custumal'), (6, 'Account Roll'), (3, 'Survey')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(1, 'Hilary'), (3, 'Trinity'), (2, 'Easter'), (4, 'Michaelmas')]),
        ),
    ]
