# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0002_auto_20170919_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(4, 'Chevage'), (1, 'Hallmoot'), (6, 'Account Roll'), (5, 'Unknown'), (3, 'Impercamentum'), (2, 'Tourn')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female'), ('I', 'Institution')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Villein'), (2, 'Free'), (4, 'Institution'), (3, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(6, 'Account Roll'), (5, 'Patent Roll'), (1, 'Court Roll'), (2, 'Extant'), (4, 'Custumal'), (3, 'Survey')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(4, 'Michaelmas'), (3, 'Trinity'), (2, 'Easter'), (1, 'Hilary')]),
        ),
    ]
