# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0003_auto_20170919_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(3, 'Impercamentum'), (6, 'Account Roll'), (2, 'Tourn'), (5, 'Unknown'), (4, 'Chevage'), (1, 'Hallmoot')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown'), ('I', 'Institution')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(3, 'Unknown'), (2, 'Free'), (4, 'Institution'), (1, 'Villein')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(6, 'Account Roll'), (2, 'Extant'), (3, 'Survey'), (5, 'Patent Roll'), (4, 'Custumal'), (1, 'Court Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (4, 'Michaelmas'), (2, 'Easter'), (1, 'Hilary')]),
        ),
    ]
