# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0003_auto_20170830_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casepeopleland',
            options={'verbose_name': 'Case to Person to Land', 'verbose_name_plural': 'Cases to People to Land'},
        ),
        migrations.AlterModelOptions(
            name='casetype',
            options={'verbose_name': 'Case Type', 'verbose_name_plural': 'Case Types'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='impercamentum',
            options={'verbose_name_plural': 'Impercamenta'},
        ),
        migrations.AlterModelOptions(
            name='landparcel',
            options={'verbose_name': 'Land Parcel', 'verbose_name_plural': 'Land Parcels'},
        ),
        migrations.AlterModelOptions(
            name='landsplit',
            options={'verbose_name': 'Land Split', 'verbose_name_plural': 'Land Splits'},
        ),
        migrations.AlterModelOptions(
            name='parceltenure',
            options={'verbose_name': 'Parcel Tenure', 'verbose_name_plural': 'Parcel Tenures'},
        ),
        migrations.AlterModelOptions(
            name='parceltype',
            options={'verbose_name': 'Parcel Type', 'verbose_name_plural': 'Parcel Types'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='placementioned',
            options={'verbose_name_plural': 'Places Mentioned'},
        ),
        migrations.AlterModelOptions(
            name='positiontype',
            options={'verbose_name': 'Position Name', 'verbose_name_plural': 'Position Names'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Relation Type', 'verbose_name_plural': 'Relation Types'},
        ),
        migrations.RenameField(
            model_name='village',
            old_name='latitute',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='person',
            name='associated_land',
            field=models.ManyToManyField(related_name='associated_land', through='peasantlegaldb.CasePeopleLand', to='peasantlegaldb.Land'),
        ),
        migrations.AddField(
            model_name='person',
            name='related',
            field=models.ManyToManyField(related_name='relations', through='peasantlegaldb.Relationship', to='peasantlegaldb.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(5, 'Unknown'), (6, 'Account Roll'), (2, 'Tourn'), (1, 'Hallmoot'), (4, 'Chevage'), (3, 'Impercamentum')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[('U', 'Unknown'), ('I', 'Institution'), ('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[('I', 'Institution'), ('U', 'Unknown'), ('F', 'Free'), ('V', 'Villein')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(5, 'Patent Roll'), (2, 'Extant'), (4, 'Custumal'), (1, 'Court Roll'), (6, 'Account Roll'), (3, 'Survey')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(1, 'Hilary'), (4, 'Michaelmas'), (2, 'Easter'), (3, 'Trinity')]),
        ),
    ]
