# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0004_auto_20170907_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='associated_land',
        ),
        migrations.RemoveField(
            model_name='person',
            name='case_roles',
        ),
        migrations.RemoveField(
            model_name='person',
            name='related',
        ),
        migrations.RemoveField(
            model_name='village',
            name='mentions',
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(4, 'Chevage'), (1, 'Hallmoot'), (6, 'Account Roll'), (5, 'Unknown'), (2, 'Tourn'), (3, 'Impercamentum')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='litigants',
            field=models.ManyToManyField(through='peasantlegaldb.Litigant', to='peasantlegaldb.Person'),
        ),
        migrations.AlterField(
            model_name='litigant',
            name='amercement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigant_amercement', to='peasantlegaldb.Money'),
        ),
        migrations.AlterField(
            model_name='litigant',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_to_person', to='peasantlegaldb.Case'),
        ),
        migrations.AlterField(
            model_name='litigant',
            name='damage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigant_damages', to='peasantlegaldb.Money'),
        ),
        migrations.AlterField(
            model_name='litigant',
            name='fine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigant_fine', to='peasantlegaldb.Money'),
        ),
        migrations.AlterField(
            model_name='litigant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_to_case', to='peasantlegaldb.Person'),
        ),
        migrations.AlterField(
            model_name='litigant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litigant_role', to='peasantlegaldb.Role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[('U', 'Unknown'), ('I', 'Institution'), ('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[('U', 'Unknown'), ('I', 'Institution'), ('F', 'Free'), ('V', 'Villein')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(4, 'Custumal'), (6, 'Account Roll'), (2, 'Extant'), (1, 'Court Roll'), (3, 'Survey'), (5, 'Patent Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(2, 'Easter'), (3, 'Trinity'), (1, 'Hilary'), (4, 'Michaelmas')]),
        ),
    ]
