# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0004_auto_20170919_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(2, 'Tourn'), (1, 'Hallmoot'), (5, 'Unknown'), (4, 'Chevage'), (3, 'Impercamentum'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('I', 'Institution'), ('M', 'Male'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(4, 'Institution'), (3, 'Unknown'), (2, 'Free'), (1, 'Villein')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(4, 'Custumal'), (1, 'Court Roll'), (5, 'Patent Roll'), (3, 'Survey'), (6, 'Account Roll'), (2, 'Extant')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(4, 'Michaelmas'), (1, 'Hilary'), (3, 'Trinity'), (2, 'Easter')]),
        ),
    ]
