# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0006_auto_20170921_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chevage',
            name='amercement',
        ),
        migrations.RemoveField(
            model_name='chevage',
            name='case',
        ),
        migrations.RemoveField(
            model_name='chevage',
            name='person',
        ),
        migrations.RemoveField(
            model_name='heriot',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='heriot',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='heriot',
            name='case',
        ),
        migrations.RemoveField(
            model_name='heriot',
            name='person',
        ),
        migrations.RemoveField(
            model_name='impercamentum',
            name='amercement',
        ),
        migrations.RemoveField(
            model_name='impercamentum',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='impercamentum',
            name='case',
        ),
        migrations.RemoveField(
            model_name='impercamentum',
            name='person',
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(1, 'Hallmoot'), (2, 'Tourn'), (6, 'Account Roll'), (4, 'Chevage'), (5, 'Unknown'), (3, 'Impercamentum')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('U', 'Unknown'), ('I', 'Institution'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(2, 'Free'), (3, 'Unknown'), (4, 'Institution'), (1, 'Villein')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(4, 'Custumal'), (6, 'Account Roll'), (3, 'Survey'), (5, 'Patent Roll'), (2, 'Extant'), (1, 'Court Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(1, 'Hilary'), (2, 'Easter'), (3, 'Trinity'), (4, 'Michaelmas')]),
        ),
        migrations.DeleteModel(
            name='Chevage',
        ),
        migrations.DeleteModel(
            name='Heriot',
        ),
        migrations.DeleteModel(
            name='Impercamentum',
        ),
    ]
