# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0007_auto_20170921_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(2, 'Tourn'), (5, 'Unknown'), (6, 'Account Roll'), (4, 'Chevage'), (3, 'Impercamentum'), (1, 'Hallmoot')]),
        ),
        migrations.AlterField(
            model_name='litigant',
            name='impercamentum_amercement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impercamentum_amercement', to='peasantlegaldb.Money'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('M', 'Male'), ('I', 'Institution')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Villein'), (4, 'Institution'), (3, 'Unknown'), (2, 'Free')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(5, 'Patent Roll'), (6, 'Account Roll'), (4, 'Custumal'), (3, 'Survey'), (2, 'Extant'), (1, 'Court Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(4, 'Michaelmas'), (3, 'Trinity'), (1, 'Hilary'), (2, 'Easter')]),
        ),
    ]
