# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0008_auto_20170922_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lands',
            field=models.ManyToManyField(through='peasantlegaldb.CasePeopleLand', to='peasantlegaldb.Land'),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(4, 'Chevage'), (1, 'Hallmoot'), (3, 'Impercamentum'), (6, 'Account Roll'), (2, 'Tourn'), (5, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='landparcel',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='peasantlegaldb.Land'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('I', 'Institution'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(4, 'Institution'), (3, 'Unknown'), (2, 'Free'), (1, 'Villein')]),
        ),
        migrations.AlterField(
            model_name='position',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='peasantlegaldb.Person'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(5, 'Patent Roll'), (1, 'Court Roll'), (2, 'Extant'), (6, 'Account Roll'), (3, 'Survey'), (4, 'Custumal')]),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_person_one', to='peasantlegaldb.Person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_person_two', to='peasantlegaldb.Person'),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (2, 'Easter'), (1, 'Hilary'), (4, 'Michaelmas')]),
        ),
    ]
