# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0009_auto_20171006_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigant',
            name='land_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_to_land', to='peasantlegaldb.Land'),
        ),
        migrations.AddField(
            model_name='litigant',
            name='land_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='litigant',
            name='land_villeinage',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(5, 'Unknown'), (1, 'Hallmoot'), (3, 'Impercamentum'), (6, 'Account Roll'), (4, 'Chevage'), (2, 'Tourn')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('I', 'Institution'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(4, 'Institution'), (1, 'Villein'), (3, 'Unknown'), (2, 'Free')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(5, 'Patent Roll'), (1, 'Court Roll'), (2, 'Extant'), (4, 'Custumal'), (6, 'Account Roll'), (3, 'Survey')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (1, 'Hilary'), (2, 'Easter'), (4, 'Michaelmas')]),
        ),
    ]
