# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0010_auto_20171006_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigant',
            old_name='land_id',
            new_name='land',
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(1, 'Hallmoot'), (6, 'Account Roll'), (5, 'Unknown'), (3, 'Impercamentum'), (2, 'Tourn'), (4, 'Chevage')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('I', 'Institution'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Villein'), (4, 'Institution'), (3, 'Unknown'), (2, 'Free')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(1, 'Court Roll'), (6, 'Account Roll'), (3, 'Survey'), (5, 'Patent Roll'), (2, 'Extant'), (4, 'Custumal')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(1, 'Hilary'), (3, 'Trinity'), (2, 'Easter'), (4, 'Michaelmas')]),
        ),
    ]
