# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0011_auto_20171006_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigant',
            old_name='heriot_assessment',
            new_name='heriot',
        ),
        migrations.RenameField(
            model_name='litigant',
            old_name='impercamentum_amercement',
            new_name='impercamentum',
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(3, 'Impercamentum'), (2, 'Tourn'), (6, 'Account Roll'), (5, 'Unknown'), (4, 'Chevage'), (1, 'Hallmoot')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('U', 'Unknown'), ('I', 'Institution'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Villein'), (4, 'Institution'), (2, 'Free'), (3, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(2, 'Extant'), (4, 'Custumal'), (5, 'Patent Roll'), (6, 'Account Roll'), (3, 'Survey'), (1, 'Court Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (2, 'Easter'), (1, 'Hilary'), (4, 'Michaelmas')]),
        ),
    ]
