# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0012_auto_20171010_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepeopleland',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casepeopleland',
            name='land',
        ),
        migrations.RemoveField(
            model_name='casepeopleland',
            name='person',
        ),
        migrations.RemoveField(
            model_name='casepeopleland',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': 'date'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='lands',
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(1, 'Hallmoot'), (5, 'Unknown'), (4, 'Chevage'), (6, 'Account Roll'), (2, 'Tourn'), (3, 'Impercamentum')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='peasantlegaldb.Session'),
        ),
        migrations.AlterField(
            model_name='cornbot',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cornbot', to='peasantlegaldb.Case'),
        ),
        migrations.AlterField(
            model_name='extrahura',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrahura', to='peasantlegaldb.Case'),
        ),
        migrations.AlterField(
            model_name='murrain',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murrain', to='peasantlegaldb.Case'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('I', 'Institution'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(4, 'Institution'), (3, 'Unknown'), (1, 'Villein'), (2, 'Free')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(1, 'Court Roll'), (3, 'Survey'), (6, 'Account Roll'), (5, 'Patent Roll'), (2, 'Extant'), (4, 'Custumal')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (2, 'Easter'), (4, 'Michaelmas'), (1, 'Hilary')]),
        ),
        migrations.DeleteModel(
            name='CasePeopleLand',
        ),
    ]
