# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0013_auto_20171014_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(3, 'Impercamentum'), (4, 'Chevage'), (2, 'Tourn'), (1, 'Hallmoot'), (5, 'Unknown'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='landparcel',
            name='parcel_tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.ParcelTenure', verbose_name='tenure'),
        ),
        migrations.AlterField(
            model_name='landparcel',
            name='parcel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peasantlegaldb.ParcelType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='money',
            name='in_denarius',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('U', 'Unknown'), ('M', 'Male'), ('I', 'Institution')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Villein'), (4, 'Institution'), (3, 'Unknown'), (2, 'Free')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(3, 'Survey'), (2, 'Extant'), (1, 'Court Roll'), (4, 'Custumal'), (5, 'Patent Roll'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(2, 'Easter'), (4, 'Michaelmas'), (3, 'Trinity'), (1, 'Hilary')]),
        ),
    ]
