# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0014_auto_20171027_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(1, 'Hallmoot'), (4, 'Chevage'), (3, 'Impercamentum'), (2, 'Tourn'), (5, 'Unknown'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('I', 'Institution'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(2, 'Free'), (3, 'Unknown'), (4, 'Institution'), (1, 'Villein')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(2, 'Extant'), (1, 'Court Roll'), (5, 'Patent Roll'), (4, 'Custumal'), (3, 'Survey'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (2, 'Easter'), (1, 'Hilary'), (4, 'Michaelmas')]),
        ),
    ]
