# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0015_auto_20171109_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(3, 'Impercamentum'), (4, 'Chevage'), (2, 'Tourn'), (1, 'Hallmoot'), (6, 'Account Roll'), (5, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('I', 'Institution'), ('U', 'Unknown'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(4, 'Institution'), (1, 'Villein'), (2, 'Free'), (3, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(1, 'Court Roll'), (2, 'Extant'), (5, 'Patent Roll'), (4, 'Custumal'), (3, 'Survey'), (6, 'Account Roll')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (1, 'Hilary'), (4, 'Michaelmas'), (2, 'Easter')]),
        ),
    ]
