# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0016_auto_20171109_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(6, 'Account Roll'), (4, 'Chevage'), (3, 'Impercamentum'), (2, 'Tourn'), (5, 'Unknown'), (1, 'Hallmoot')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('I', 'Institution'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(3, 'Unknown'), (2, 'Free'), (4, 'Institution'), (1, 'Villein')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(5, 'Patent Roll'), (1, 'Court Roll'), (4, 'Custumal'), (6, 'Account Roll'), (2, 'Extant'), (3, 'Survey')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (4, 'Michaelmas'), (2, 'Easter'), (1, 'Hilary')]),
        ),
    ]
