# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peasantlegaldb', '0017_auto_20171109_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.IntegerField(choices=[(6, 'Account Roll'), (1, 'Hallmoot'), (4, 'Chevage'), (5, 'Unknown'), (3, 'Impercamentum'), (2, 'Tourn')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('U', 'Unknown'), ('I', 'Institution'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.IntegerField(choices=[(1, 'Court Roll'), (6, 'Account Roll'), (4, 'Custumal'), (2, 'Extant'), (3, 'Survey'), (5, 'Patent Roll')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='reel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_term',
            field=models.IntegerField(choices=[(3, 'Trinity'), (4, 'Michaelmas'), (1, 'Hilary'), (2, 'Easter')]),
        ),
    ]
